<div id='grid'>
    <form method="POST">
        <? if(isset($this->buttons['grid_1_1'])) : ?>
            <div id='grid_1_1' />
        <? else: ?>
            <input type='submit' class='grid_button' id='grid_1_1' name='grid_1_1' />
        <? endif; ?>
        <input type='submit' class='grid_button' />
        <input type='submit' class='grid_button' />
        <input type='submit' class='grid_button' />
        <input type='submit' class='grid_button' />
        <input type='submit' class='grid_button' />
        <input type='submit' class='grid_button' />
        <input type='submit' class='grid_button' />
        <input type='submit' class='grid_button' />
    </form>
</div>
